future: true
permalink: /:title/
url: http://muahao.github.io
name: Ahao Mu
author: Ahao Mu
email: ahao.muu@gmail.com
duoshuo: Ahao Mu
beian: 
cnzz: 
weibo: Ahao Mu
github: Ahao Mu
paginate: 20
highlighter: rouge
truncate: true
about: "Ahao Mu"
